[package]
name = "executor"
version = "0.1.0"
edition = "2021"
authors = ["Fangliang Zhao <1491657576@qq.com>"]
description = "An out-of-the-box executor that can be used in multiple operating systems"
license = "MIT"
repository = "https://github.com/AsyncModules/executor"

[dependencies]
